/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tasod_graphics_RenderEngine */

#ifndef _Included_tasod_graphics_RenderEngine
#define _Included_tasod_graphics_RenderEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tasod_graphics_RenderEngine
 * Method:    method
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tasod_graphics_RenderEngine_method
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
